### ISSUE TITLE
Radiance Parameters json

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/honeybee-json#2]
Finally getting to implement radiance parameters to json. Looking at it i'm thinking the simplest/most reliable way forward is to simply use the "to_string" and "from_string" method wrapped in a json format like so:

    def to_json(self):
        """Write radiance parameters to json.
        """
        return {"gridbased_parameters": self.to_rad_string()
                }

Does that seem dangerous/lazy?

**Comment by mostaphaRoudsari** [comment]
This will work fine as far as you implement the `from_json` to use `import_parameter_values_from_string`

https://github.com/ladybug-tools/honeybee/blob/a4d91756891bc92bda5f04df342431bfbcaa8814/honeybee/radiance/parameters/_parametersbase.py#L170

**Comment by AntoineDao** [comment]
was on line 170 of that method just now!

**Comment by AntoineDao** [comment]
Fixed [here](https://github.com/ladybug-tools/honeybee/pull/199)
